### ISSUE TITLE
Text overlapping

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1675-assignment-1#1]
Currently trying to get my first figcaption and first h2 to not overlap at 240px. Unfortunately, my attempts so far have not worked.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
What I would probably do is not use `position: absolute` at 240px, but just have the caption underneath the image... or make the image a background image instead and let the browser crop it to fit using `background-size: cover`.
