### ISSUE TITLE
Nav and h1 conflict

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1675-assignment-1#3]
I've been attempting to get my nav and h1 to stop overlapping in a way that the nav shows it's background colour. I've been doing a lot of fiddling, so somethings might be unhelpful to straighten it out.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
I think there’s two things causing the problem:
1. Remove the height from the `<h1>`—try to avoid heights at all costs.
2. Instead of `clear: both` on the `<nav>` add `overflow: hidden`.
